
format:
	julia -e "using JuliaFormatter; format(\".\");"

test:
	julia --project="../../c06_confidence" runtests.jl

test_l0601_onePopVKnown:
	julia --project="../../c06_confidence" test_l0601_onePopVKnown.jl
test_l0602_onePopVUnknown:
	julia --project="../../c06_confidence" test_l0602_onePopVUnknown.jl
test_l0603_twoPopVKnown:
	julia --project="../../c06_confidence" test_l0603_twoPopVKnown.jl
test_l0604_twoPopMVUnknownAEqual:
	julia --project="../../c06_confidence" test_l0604_twoPopMVUnknownAEqual.jl
test_l0605_twoPopMVUnknownAUnequal:
	julia --project="../../c06_confidence" test_l0605_twoPopMVUnknownAUnequal.jl
test_l0606_vDOF_comparison:
	julia --project="../../c06_confidence" test_l0606_vDOF_comparison.jl
test_l0607_proportionCI:
	julia --project="../../c06_confidence" test_l0607_proportionCI.jl
test_l0608_proportionCIsampleSize:
	julia --project="../../c06_confidence" test_l0608_proportionCIsampleSize.jl
test_l0609_propCIcoverageAccuracy:
	julia --project="../../c06_confidence" test_l0609_propCIcoverageAccuracy.jl
test_l0610_varianceCI:
	julia --project="../../c06_confidence" test_l0610_varianceCI.jl
test_l0611_sampleVarDists:
	julia --project="../../c06_confidence" test_l0611_sampleVarDists.jl
test_l0612_varianceCIalphas:
	julia --project="../../c06_confidence" test_l0612_varianceCIalphas.jl
test_l0613_bCI:
	julia --project="../../c06_confidence" test_l0613_bCI.jl
test_l0614_bootstrapCI:
	julia --project="../../c06_confidence" test_l0614_bootstrapCI.jl
test_l0615_predictionInterval:
	julia --project="../../c06_confidence" test_l0615_predictionInterval.jl
test_l0616_credible:
	julia --project="../../c06_confidence" test_l0616_credible.jl
