using Pkg
path_to_here = @__DIR__
Pkg.activate("$path_to_here")
Pkg.add("HCubature")
Pkg.add("Plots")
Pkg.add("StatsBase")
Pkg.add("Distributions")
Pkg.add("Statistics")
Pkg.add("SpecialFunctions")
Pkg.add("PyPlot")
Pkg.add("LinearAlgebra")
Pkg.add("Measures")
Pkg.add("LaTeXStrings")
Pkg.add("QuadGK")
Pkg.add("Calculus")
Pkg.add("Random")
Pkg.precompile()