
format:
	julia -e "using JuliaFormatter; format(\".\");"

test:
	julia --project="../../c05_inference" runtests.jl

test_l0501_statisticsOfARandomSample:
	julia --project="../../c05_inference" test_l0501_statisticsOfARandomSample.jl
test_l0502_friendOfANormalDistribution:
	julia --project="../../c05_inference" test_l0502_friendOfANormalDistribution.jl
test_l0503_meanVarIndependence:
	julia --project="../../c05_inference" test_l0503_meanVarIndependence.jl
test_l0504_tDistribution:
	julia --project="../../c05_inference" test_l0504_tDistribution.jl
test_l0505_fDistribution:
	julia --project="../../c05_inference" test_l0505_fDistribution.jl
test_l0506_centralLimitTheorem:
	julia --project="../../c05_inference" test_l0506_centralLimitTheorem.jl
test_l0507_stdVarBiasEstimate:
	julia --project="../../c05_inference" test_l0507_stdVarBiasEstimate.jl
test_l0508_parametersNumerical:
	julia --project="../../c05_inference" test_l0508_parametersNumerical.jl
test_l0509_gammaLikelihood:
	julia --project="../../c05_inference" test_l0509_gammaLikelihood.jl
test_l0510_mleGamma:
	julia --project="../../c05_inference" test_l0510_mleGamma.jl
test_l0511_mm_vs_mle:
	julia --project="../../c05_inference" test_l0511_mm_vs_mle.jl
test_l0512_confidenceIntervalConcept:
	julia --project="../../c05_inference" test_l0512_confidenceIntervalConcept.jl
test_l0513_ciCoverage:
	julia --project="../../c05_inference" test_l0513_ciCoverage.jl
test_l0514_teststatPvalRejectregion:
	julia --project="../../c05_inference" test_l0514_teststatPvalRejectregion.jl
test_l0515_simpleHypothesisTest:
	julia --project="../../c05_inference" test_l0515_simpleHypothesisTest.jl
test_l0516_receiverOperatingCurve:
	julia --project="../../c05_inference" test_l0516_receiverOperatingCurve.jl
test_l0517_randomizationTest:
	julia --project="../../c05_inference" test_l0517_randomizationTest.jl
test_l0518_bayesUnivariate:
	julia --project="../../c05_inference" test_l0518_bayesUnivariate.jl
test_l0519_bayesUnivariateConjugate:
	julia --project="../../c05_inference" test_l0519_bayesUnivariateConjugate.jl
test_l0520_bayesMCMC:
	julia --project="../../c05_inference" test_l0520_bayesMCMC.jl