Project.toml:
	julia setup.jl

l0601_onePopVKnown:
	julia --project=. l0601_onePopVKnown.jl
l0602_onePopVUnknown:
	julia --project=. l0602_onePopVUnknown.jl
l0603_twoPopVKnown:
	julia --project=. l0603_twoPopVKnown.jl
l0604_twoPopMVUnknownAEqual:
	julia --project=. l0604_twoPopMVUnknownAEqual.jl
l0605_twoPopMVUnknownAUnequal:
	julia --project=. l0605_twoPopMVUnknownAUnequal.jl
l0606_vDOF_comparison:
	julia --project=. l0606_vDOF_comparison.jl
l0607_proportionCI:
	julia --project=. l0607_proportionCI.jl
l0608_proportionCIsampleSize:
	julia --project=. l0608_proportionCIsampleSize.jl
l0609_propCIcoverageAccuracy:
	julia --project=. l0609_propCIcoverageAccuracy.jl
l0610_varianceCI:
	julia --project=. l0610_varianceCI.jl
l0611_sampleVarDists:
	julia --project=. l0611_sampleVarDists.jl
l0612_varianceCIalphas:
	julia --project=. l0612_varianceCIalphas.jl
l0613_bCI:
	julia --project=. l0613_bCI.jl
l0614_bootstrapCI:
	julia --project=. l0614_bootstrapCI.jl
l0615_predictionInterval:
	julia --project=. l0615_predictionInterval.jl
l0616_credible:
	julia --project=. l0616_credible.jl