all: l0701_infMeanSingleVarKnown l0702_infMeanSingleVarUnknown l0703_signTest l0704_TvsSign l0705_infMeanDiffVarKnown l0706_infMeanDiffVarAssumedEqual l0707_infMeanDiffVarAssumedUnequal l0708_dataBoxPlot l0708_sampleMeansANOVA l0709_ssDecomposition l0710_anovaFTest l0711_anovaFDistribution l0712_chiSqTest l0713_chiSqIndependence l0714_ksStatistic l0715_ksBrownian l0716_wald_wolfowitz l0717_power l0718_powerCurves l0719_pValDist

Project.toml:
	julia setup.jl

l0701_infMeanSingleVarKnown:
	julia --project=. l0701_infMeanSingleVarKnown.jl
l0702_infMeanSingleVarUnknown:
	julia --project=. l0702_infMeanSingleVarUnknown.jl
l0703_signTest:
	julia --project=. l0703_signTest.jl
l0704_TvsSign:
	julia --project=. l0704_TvsSign.jl
l0705_infMeanDiffVarKnown:
	julia --project=. l0705_infMeanDiffVarKnown.jl
l0706_infMeanDiffVarAssumedEqual:
	julia --project=. l0706_infMeanDiffVarAssumedEqual.jl
l0707_infMeanDiffVarAssumedUnequal:
	julia --project=. l0707_infMeanDiffVarAssumedUnequal.jl
l0708_dataBoxPlot:
	julia --project=. l0708_dataBoxPlot.jl
l0708_sampleMeansANOVA:
	julia --project=. l0708_sampleMeansANOVA.jl
l0709_ssDecomposition:
	julia --project=. l0709_ssDecomposition.jl
l0710_anovaFTest:
	julia --project=. l0710_anovaFTest.jl
l0711_anovaFDistribution:
	julia --project=. l0711_anovaFDistribution.jl
l0712_chiSqTest:
	julia --project=. l0712_chiSqTest.jl
l0713_chiSqIndependence:
	julia --project=. l0713_chiSqIndependence.jl
l0714_ksStatistic:
	julia --project=. l0714_ksStatistic.jl
l0715_ksBrownian:
	julia --project=. l0715_ksBrownian.jl
l0716_wald_wolfowitz:
	julia --project=. l0716_wald_wolfowitz.jl
l0717_power:
	julia --project=. l0717_power.jl
l0718_powerCurves:
	julia --project=. l0718_powerCurves.jl
l0719_pValDist:
	julia --project=. l0719_pValDist.jl