
module c05_inference
    include("l0501_statisticsOfARandomSample.jl")
    include("l0502_friendOfANormalDistribution.jl")
    include("l0503_meanVarIndependence.jl")
    include("l0504_tDistribution.jl")
    include("l0505_fDistribution.jl")
    include("l0506_centralLimitTheorem.jl")
    include("l0507_stdVarBiasEstimate.jl")
    include("l0508_parametersNumerical.jl")
    include("l0509_gammaLikelihood.jl")
    include("l0510_mleGamma.jl")
    include("l0511_mm_vs_mle.jl")
    include("l0512_confidenceIntervalConcept.jl")
    include("l0513_ciCoverage.jl")
    include("l0514_teststatPvalRejectregion.jl")
    include("l0515_simpleHypothesisTest.jl")
    include("l0516_receiverOperatingCurve.jl")
    include("l0517_randomizationTest.jl")
    include("l0518_bayesUnivariate.jl")
    include("l0519_bayesUnivariateConjugate.jl")
    include("l0520_bayesMCMC.jl")
end