

test:
	julia --project="/mnt/SSD1/mrepos/github.com/wilsonify/statistics-with-julia/c02_probability" runtests.jl

test_l0201_diceSumEven:
	julia --project="/mnt/SSD1/mrepos/github.com/wilsonify/statistics-with-julia/c02_probability" test_l0201_diceSumEven.jl
test_l0202_passwords:
	julia --project="/mnt/SSD1/mrepos/github.com/wilsonify/statistics-with-julia/c02_probability" test_l0202_passwords.jl
test_l0203_birthdayProblem:
	julia --project="/mnt/SSD1/mrepos/github.com/wilsonify/statistics-with-julia/c02_probability" test_l0203_birthdayProblem.jl
test_l0204_fishing:
	julia --project="/mnt/SSD1/mrepos/github.com/wilsonify/statistics-with-julia/c02_probability" test_l0204_fishing.jl
test_l0205_catalan:
	julia --project="/mnt/SSD1/mrepos/github.com/wilsonify/statistics-with-julia/c02_probability" test_l0205_catalan.jl
test_l0206_sets:
	julia --project="/mnt/SSD1/mrepos/github.com/wilsonify/statistics-with-julia/c02_probability" test_l0206_sets.jl
test_l0207_mcFalacy:
	julia --project="/mnt/SSD1/mrepos/github.com/wilsonify/statistics-with-julia/c02_probability" test_l0207_mcFalacy.jl
test_l0208_secretaryEnvelopes:
	julia --project="/mnt/SSD1/mrepos/github.com/wilsonify/statistics-with-julia/c02_probability" test_l0208_secretaryEnvelopes.jl
test_l0209_occupancyProblem:
	julia --project="/mnt/SSD1/mrepos/github.com/wilsonify/statistics-with-julia/c02_probability" test_l0209_occupancyProblem.jl
test_l0210_independence:
	julia --project="/mnt/SSD1/mrepos/github.com/wilsonify/statistics-with-julia/c02_probability" test_l0210_independence.jl
test_l0211_conditionalProbability:
	julia --project="/mnt/SSD1/mrepos/github.com/wilsonify/statistics-with-julia/c02_probability" test_l0211_conditionalProbability.jl
test_l0212_txRxBayes:
	julia --project="/mnt/SSD1/mrepos/github.com/wilsonify/statistics-with-julia/c02_probability" test_l0212_txRxBayes.jl
test_l0213_montyHall:
	julia --project="/mnt/SSD1/mrepos/github.com/wilsonify/statistics-with-julia/c02_probability" test_l0213_montyHall.jl

