all: l0501_statisticsOfARandomSample l0502_friendOfANormalDistribution l0503_meanVarIndependence l0504_tDistribution l0505_fDistribution l0506_centralLimitTheorem l0507_stdVarBiasEstimate l0508_parametersNumerical l0509_gammaLikelihood l0510_mleGamma l0511_mm_vs_mle l0512_confidenceIntervalConcept l0513_ciCoverage l0514_teststatPvalRejectregion l0515_simpleHypothesisTest l0516_receiverOperatingCurve l0517_randomizationTest l0518_bayesUnivariate l0519_bayesUnivariateConjugate l0520_bayesMCMC

clean:
	julia -e "using Pkg; Pkg.gc();"

Project.toml:
	julia setup.jl

l0501_statisticsOfARandomSample:
	julia --project=. l0501_statisticsOfARandomSample.jl
l0502_friendOfANormalDistribution:
	julia --project=. l0502_friendOfANormalDistribution.jl
l0503_meanVarIndependence:
	julia --project=. l0503_meanVarIndependence.jl
l0504_tDistribution:
	julia --project=. l0504_tDistribution.jl
l0505_fDistribution:
	julia --project=. l0505_fDistribution.jl
l0506_centralLimitTheorem:
	julia --project=. l0506_centralLimitTheorem.jl
l0507_stdVarBiasEstimate:
	julia --project=. l0507_stdVarBiasEstimate.jl
l0508_parametersNumerical:
	julia --project=. l0508_parametersNumerical.jl
l0509_gammaLikelihood:
	julia --project=. l0509_gammaLikelihood.jl
l0510_mleGamma:
	julia --project=. l0510_mleGamma.jl
l0511_mm_vs_mle:
	julia --project=. l0511_mm_vs_mle.jl
l0512_confidenceIntervalConcept:
	julia --project=. l0512_confidenceIntervalConcept.jl
l0513_ciCoverage:
	julia --project=. l0513_ciCoverage.jl
l0514_teststatPvalRejectregion:
	julia --project=. l0514_teststatPvalRejectregion.jl
l0515_simpleHypothesisTest:
	julia --project=. l0515_simpleHypothesisTest.jl
l0516_receiverOperatingCurve:
	julia --project=. l0516_receiverOperatingCurve.jl
l0517_randomizationTest:
	julia --project=. l0517_randomizationTest.jl
l0518_bayesUnivariate:
	julia --project=. l0518_bayesUnivariate.jl
l0519_bayesUnivariateConjugate:
	julia --project=. l0519_bayesUnivariateConjugate.jl
l0520_bayesMCMC:
	julia --project=. l0520_bayesMCMC.jl