JULIA=/opt/julia/v1.5.4/bin/julia
PROJECT="/home/thom/.julia/environments/v1.5"

# PROJECT="/home/thom/.julia/environments/StatisticsWithJulia1.9"

format:
	${JULIA} -e "using ${JULIA}Formatter; format(\".\");"

test:
	${JULIA} --project=${PROJECT} runtests.jl

test_l0401_callByValueByReference:
	${JULIA} --project=${PROJECT} test_l0401_callByValueByReference.jl
test_l0402_shallowDeepCopy:
	${JULIA} --project=${PROJECT} test_l0402_shallowDeepCopy.jl
test_l0403_dataframeInspection:
	${JULIA} --project=${PROJECT} test_l0403_dataframeInspection.jl
test_l0404_dataframeReferencing:
	${JULIA} --project=${PROJECT} test_l0404_dataframeReferencing.jl
test_l0405_dataframeEditing:
	${JULIA} --project=${PROJECT} test_l0405_dataframeEditing.jl
test_l0406_dataframeCopyDeepCopy:
	${JULIA} --project=${PROJECT} test_l0406_dataframeCopyDeepCopy.jl
test_l0407_dataframeMissing:
	${JULIA} --project=${PROJECT} test_l0407_dataframeMissing.jl
test_l0408_dataframeReshape:
	${JULIA} --project=${PROJECT} test_l0408_dataframeReshape.jl
test_l0409_dataframeOperations:
	${JULIA} --project=${PROJECT} test_l0409_dataframeOperations.jl
test_l0410_dataframeImputation:
	${JULIA} --project=${PROJECT} test_l0410_dataframeImputation.jl
test_l0411_summarizingData:
	${JULIA} --project=${PROJECT} test_l0411_summarizingData.jl
test_l0412_meanVectCovMatrixSummary:
	${JULIA} --project=${PROJECT} test_l0412_meanVectCovMatrixSummary.jl
test_l0413_sampleCovarianceMatrix:
	${JULIA} --project=${PROJECT} test_l0413_sampleCovarianceMatrix.jl
test_l0414_manualHistogram:
	${JULIA} --project=${PROJECT} test_l0414_manualHistogram.jl
test_l0415_statsPlotsDensity:
	${JULIA} --project=${PROJECT} test_l0415_statsPlotsDensity.jl
test_l0416_KDE:
	${JULIA} --project=${PROJECT} test_l0416_KDE.jl
test_l0417_ecdf:
	${JULIA} --project=${PROJECT} test_l0417_ecdf.jl
test_l0418_normalProbabilityPlot:
	${JULIA} --project=${PROJECT} test_l0418_normalProbabilityPlot.jl
test_l0419_multipleSimplePlot:
	${JULIA} --project=${PROJECT} test_l0419_multipleSimplePlot.jl
test_l0420_radialPlot:
	${JULIA} --project=${PROJECT} test_l0420_radialPlot.jl
test_l0421_qqPlot:
	${JULIA} --project=${PROJECT} test_l0421_qqPlot.jl
test_l0422_boxplot:
	${JULIA} --project=${PROJECT} test_l0422_boxplot.jl
test_l0423_violinPlot:
	${JULIA} --project=${PROJECT} test_l0423_violinPlot.jl
test_l0424_scatterplot:
	${JULIA} --project=${PROJECT} test_l0424_scatterplot.jl
test_l0424_scatterplotMatrix:
	${JULIA} --project=${PROJECT} test_l0424_scatterplotMatrix.jl
test_l0425_marginalHists:
	${JULIA} --project=${PROJECT} test_l0425_marginalHists.jl
test_l0426_andrewsPlot:
	${JULIA} --project=${PROJECT} test_l0426_andrewsPlot.jl
test_l0427_pieChart:
	${JULIA} --project=${PROJECT} test_l0427_pieChart.jl
test_l0428_barPlots:
	${JULIA} --project=${PROJECT} test_l0428_barPlots.jl
test_l0429_stackplot:
	${JULIA} --project=${PROJECT} test_l0429_stackplot.jl
test_l0430_lineSearch:
	${JULIA} --project=${PROJECT} test_l0430_lineSearch.jl
test_l0431_directorySearch:
	${JULIA} --project=${PROJECT} test_l0431_directorySearch.jl






