
all: l0101_helloWorld l0102_comprehension l0103_slow l0104_fast l0105_scope l0106_bubbleSort l0107_polyRoots l0108_multiWayMarkovChainStationary l0110_plotSimple l0111_hailstoneHistogram l0112_graph l0113_imageProcessing l0114_seedExample l0115_piEstimate l0116_lcg l0117_randomWalks

environment:
	julia setup.jl

l0101_helloWorld:
	julia --project=. l0101_helloWorld.jl
l0102_comprehension:
	julia --project=. l0102_comprehension.jl
l0103_slow:
	julia --project=. l0103_slow.jl
l0104_fast:
	julia --project=. l0104_fast.jl
l0105_scope:
	julia --project=. l0105_scope.jl
l0106_bubbleSort:
	julia --project=. l0106_bubbleSort.jl
l0107_polyRoots:
	julia --project=. l0107_polyRoots.jl
l0108_multiWayMarkovChainStationary:
	julia --project=. l0108_multiWayMarkovChainStationary.jl
l0110_plotSimple:
	julia --project=. l0110_plotSimple.jl
l0111_hailstoneHistogram:
	julia --project=. l0111_hailstoneHistogram.jl
l0112_graph:
	julia --project=. l0112_graph.jl
l0113_imageProcessing:
	julia --project=. l0113_imageProcessing.jl
l0114_seedExample:
	julia --project=. l0114_seedExample.jl
graph.gif:
	julia --project=. l0115_piEstimate.jl
l0116_lcg:
	julia --project=. l0116_lcg.jl
l0117_randomWalks:
	julia --project=. l0117_randomWalks.jl