
environment:
	julia --project . setupPyCall.jl
	pip install -r requirements.txt
	python -m nltk.downloader punkt

l0101_helloWorld:
	julia --project=. l0101_helloWorld.jl
l0102_comprehension:
	julia --project=. l0102_comprehension.jl
l0103_slow:
	julia --project=. l0103_slow.jl
l0104_fast:
	julia --project=. l0104_fast.jl
l0105_scope:
	julia --project=. l0105_scope.jl
l0106_bubbleSort:
	julia --project=. l0106_bubbleSort.jl
l0107_polyRoots:
	julia --project=. l0107_polyRoots.jl
l0108_multiWayMarkovChainStationary:
	julia --project=. l0108_multiWayMarkovChainStationary.jl
l0109_shakespeareWords:
	julia --project=. l0109_shakespeareWords.jl
l0110_plotSimple:
	PYTHON=$(shell which python) julia --project=. l0110_plotSimple.jl
l0111_hailstoneHistogram:
	PYTHON=$(shell which python) julia --project=. l0111_hailstoneHistogram.jl
l0112_graph:
	PYTHON=$(shell which python) julia --project=. l0112_graph.jl
l0113_imageProcessing:
	PYTHON=$(shell which python) julia --project=. l0113_imageProcessing.jl
l0114_seedExample:
	julia --project=. l0114_seedExample.jl
graph.gif:
	julia --project=. l0115_piEstimate.jl
l0116_lcg:
	julia --project=. l0116_lcg.jl
l0117_randomWalks:
	julia --project=. l0117_randomWalks.jl
l0118_usingR:
	julia --project=. l0118_usingR.jl
l0120_usingPython:
	PYTHON=$(shell which python) julia --project=. l0120_usingPython.jl