
all: l0101_helloWorld l0102_comprehension l0103_slow l0104_fast l0105_scope l0106_bubbleSort l0107_polyRoots l0108_multiWayMarkovChainStationary l0110_plotSimple l0111_hailstoneHistogram l0112_graph l0113_imageProcessing l0114_seedExample l0115_piEstimate l0116_lcg l0117_randomWalks l0118_usingR l0120_sentiment l0120_setupPyCall l0120_usingPython l0121_usingC

environment:
	julia setup.jl

l0120_usingPython:
	PYTHON=$(shell which python) julia --project=. l0120_usingPython.jl

l0121_usingPython:
	julia --project=. l0121_usingC.jl