all: l1001_predatorPrey l1002_springMass l1003_seir l1004_simpleMarkov l1005_mcTransientCalculation l1006_catMouse l1007_qMatrixSimulation l1008_mm1Gillespie l1009_SEIRStoch l1010_DESqueue l1011_mm1DESwaitingTimes l1012_predatorPreyStoch l1013_kalman l1013_temperatureNoise l1014_reliability l1015_networkLifeTime l1016_basicCRN l1017_twoRNGs

Project1.toml:
	julia setup.jl

l1001_predatorPrey:
	julia --project=. l1001_predatorPrey.jl
l1002_springMass:
	julia --project=. l1002_springMass.jl
l1003_seir:
	julia --project=. l1003_seir.jl
l1004_simpleMarkov:
	julia --project=. l1004_simpleMarkov.jl
l1005_mcTransientCalculation:
	julia --project=. l1005_mcTransientCalculation.jl
l1006_catMouse:
	julia --project=. l1006_catMouse.jl
l1007_qMatrixSimulation:
	julia --project=. l1007_qMatrixSimulation.jl
l1008_mm1Gillespie:
	julia --project=. l1008_mm1Gillespie.jl
l1009_SEIRStoch:
	julia --project=. l1009_SEIRStoch.jl
l1010_DESqueue:
	julia --project=. l1010_DESqueue.jl
l1011_mm1DESwaitingTimes:
	julia --project=. l1011_mm1DESwaitingTimes.jl
l1012_predatorPreyStoch:
	julia --project=. l1012_predatorPreyStoch.jl
l1013_kalman:
	julia --project=. l1013_kalman.jl
l1013_temperatureNoise:
	julia --project=. l1013_temperatureNoise.jl
l1014_reliability:
	julia --project=. l1014_reliability.jl
l1015_networkLifeTime:
	julia --project=. l1015_networkLifeTime.jl
l1016_basicCRN:
	julia --project=. l1016_basicCRN.jl
l1017_twoRNGs:
	julia --project=. l1017_twoRNGs.jl