JULIA=/opt/julia/v1.5.4/bin/julia
PROJECT="/home/thom/.julia/environments/v1.5"

test:
	${JULIA} --project=${PROJECT} runtests.jl

test_l0101_helloWorld:
	${JULIA} --project=${PROJECT} test_l0101_helloWorld.jl
test_l0102_comprehension:
	${JULIA} --project=${PROJECT} test_l0102_comprehension.jl
test_l0103_slow:
	${JULIA} --project=${PROJECT} test_l0103_slow.jl
test_l0104_fast:
	${JULIA} --project=${PROJECT} test_l0104_fast.jl
test_l0105_scope:
	${JULIA} --project=${PROJECT} test_l0105_scope.jl
test_l0106_bubbleSort:
	${JULIA} --project=${PROJECT} test_l0106_bubbleSort.jl
test_l0107_polyRoots:
	${JULIA} --project=${PROJECT} test_l0107_polyRoots.jl
test_l0108_multiWayMarkovChainStationary:
	${JULIA} --project=${PROJECT} test_l0108_multiWayMarkovChainStationary.jl
test_l0110_plotSimple:
	${JULIA} --project=${PROJECT} test_l0110_plotSimple.jl
test_l0111_hailstoneHistogram:
	${JULIA} --project=${PROJECT} test_l0111_hailstoneHistogram.jl
test_l0112_graph:
	${JULIA} --project=${PROJECT} test_l0112_graph.jl
test_l0113_imageProcessing:
	${JULIA} --project=${PROJECT} test_l0113_imageProcessing.jl
test_l0114_seedExample:
	${JULIA} --project=${PROJECT} test_l0114_seedExample.jl
test_l0115_piEstimate:
	${JULIA} --project=${PROJECT} test_l0115_piEstimate.jl
test_l0116_lcg:
	${JULIA} --project=${PROJECT} test_l0116_lcg.jl
test_l0117_randomWalks:
	${JULIA} --project=${PROJECT} test_l0117_randomWalks.jl
