
test:
	/opt/julia/v1.9.3/bin/julia --project="~/.julia/environments/v1.9" runtests.jl

test_l0101_helloWorld:
	/opt/julia/v1.9.3/bin/julia --project="~/.julia/environments/v1.9" test_l0101_helloWorld.jl
test_l0102_comprehension:
	/opt/julia/v1.9.3/bin/julia --project="~/.julia/environments/v1.9" test_l0102_comprehension.jl
test_l0103_slow:
	/opt/julia/v1.9.3/bin/julia --project="~/.julia/environments/v1.9" test_l0103_slow.jl
test_l0104_fast:
	/opt/julia/v1.9.3/bin/julia --project="~/.julia/environments/v1.9" test_l0104_fast.jl
test_l0105_scope:
	/opt/julia/v1.9.3/bin/julia --project="~/.julia/environments/v1.9" test_l0105_scope.jl
test_l0106_bubbleSort:
	/opt/julia/v1.9.3/bin/julia --project="~/.julia/environments/v1.9" test_l0106_bubbleSort.jl
test_l0107_polyRoots:
	/opt/julia/v1.9.3/bin/julia --project="~/.julia/environments/v1.9" test_l0107_polyRoots.jl
test_l0108_multiWayMarkovChainStationary:
	/opt/julia/v1.9.3/bin/julia --project="~/.julia/environments/v1.9" test_l0108_multiWayMarkovChainStationary.jl
test_l0110_plotSimple:
	/opt/julia/v1.9.3/bin/julia --project="~/.julia/environments/v1.9" test_l0110_plotSimple.jl
test_l0111_hailstoneHistogram:
	/opt/julia/v1.9.3/bin/julia --project="~/.julia/environments/v1.9" test_l0111_hailstoneHistogram.jl
test_l0112_graph:
	/opt/julia/v1.9.3/bin/julia --project="~/.julia/environments/v1.9" test_l0112_graph.jl
test_l0113_imageProcessing:
	/opt/julia/v1.9.3/bin/julia --project="~/.julia/environments/v1.9" test_l0113_imageProcessing.jl
test_l0114_seedExample:
	/opt/julia/v1.9.3/bin/julia --project="~/.julia/environments/v1.9" test_l0114_seedExample.jl
test_l0115_piEstimate:
	/opt/julia/v1.9.3/bin/julia --project="~/.julia/environments/v1.9" test_l0115_piEstimate.jl
test_l0116_lcg:
	/opt/julia/v1.9.3/bin/julia --project="~/.julia/environments/v1.9" test_l0116_lcg.jl
test_l0117_randomWalks:
	/opt/julia/v1.9.3/bin/julia --project="~/.julia/environments/v1.9" test_l0117_randomWalks.jl
