PROJECT="/home/thom/.julia/environments/StatisticsWithJulia1.9"

format:
	julia -e "using JuliaFormatter; format(\".\");"

test:
	julia --project=${PROJECT} runtests.jl

test_l0401_callByValueByReference:
	julia --project=${PROJECT} test_l0401_callByValueByReference.jl
test_l0402_shallowDeepCopy:
	julia --project=${PROJECT} test_l0402_shallowDeepCopy.jl
test_l0403_dataframeInspection:
	julia --project=${PROJECT} test_l0403_dataframeInspection.jl
test_l0404_dataframeReferencing:
	julia --project=${PROJECT} test_l0404_dataframeReferencing.jl
test_l0405_dataframeEditing:
	julia --project=${PROJECT} test_l0405_dataframeEditing.jl
test_l0406_dataframeCopyDeepCopy:
	julia --project=${PROJECT} test_l0406_dataframeCopyDeepCopy.jl
test_l0407_dataframeMissing:
	julia --project=${PROJECT} test_l0407_dataframeMissing.jl
test_l0408_dataframeReshape:
	julia --project=${PROJECT} test_l0408_dataframeReshape.jl
test_l0409_dataframeOperations:
	julia --project=${PROJECT} test_l0409_dataframeOperations.jl
test_l0410_dataframeImputation:
	julia --project=${PROJECT} test_l0410_dataframeImputation.jl
test_l0411_summarizingData:
	julia --project=${PROJECT} test_l0411_summarizingData.jl
test_l0412_meanVectCovMatrixSummary:
	julia --project=${PROJECT} test_l0412_meanVectCovMatrixSummary.jl
test_l0413_sampleCovarianceMatrix:
	julia --project=${PROJECT} test_l0413_sampleCovarianceMatrix.jl
test_l0414_manualHistogram:
	julia --project=${PROJECT} test_l0414_manualHistogram.jl
test_l0415_statsPlotsDensity:
	julia --project=${PROJECT} test_l0415_statsPlotsDensity.jl
test_l0416_KDE:
	julia --project=${PROJECT} test_l0416_KDE.jl
test_l0417_ecdf:
	julia --project=${PROJECT} test_l0417_ecdf.jl
test_l0418_normalProbabilityPlot:
	julia --project=${PROJECT} test_l0418_normalProbabilityPlot.jl
test_l0419_multipleSimplePlot:
	julia --project=${PROJECT} test_l0419_multipleSimplePlot.jl
test_l0420_radialPlot:
	julia --project=${PROJECT} test_l0420_radialPlot.jl
test_l0421_qqPlot:
	julia --project=${PROJECT} test_l0421_qqPlot.jl
test_l0422_boxplot:
	julia --project=${PROJECT} test_l0422_boxplot.jl
test_l0423_violinPlot:
	julia --project=${PROJECT} test_l0423_violinPlot.jl
test_l0424_scatterplot:
	julia --project=${PROJECT} test_l0424_scatterplot.jl
test_l0424_scatterplotMatrix:
	julia --project=${PROJECT} test_l0424_scatterplotMatrix.jl
test_l0425_marginalHists:
	julia --project=${PROJECT} test_l0425_marginalHists.jl
test_l0426_andrewsPlot:
	julia --project=${PROJECT} test_l0426_andrewsPlot.jl
test_l0427_pieChart:
	julia --project=${PROJECT} test_l0427_pieChart.jl
test_l0428_barPlots:
	julia --project=${PROJECT} test_l0428_barPlots.jl
test_l0429_stackplot:
	julia --project=${PROJECT} test_l0429_stackplot.jl
test_l0430_lineSearch:
	julia --project=${PROJECT} test_l0430_lineSearch.jl
test_l0431_directorySearch:
	julia --project=${PROJECT} test_l0431_directorySearch.jl






