using Pkg
path_to_here = @__DIR__
Pkg.activate("$path_to_here")
Pkg.add("GLM")
Pkg.add("PyPlot")
Pkg.add("RDatasets")
Pkg.add("LIBSVM")
Pkg.add("Statistics")
Pkg.add("Distributions")
Pkg.add("StatsBase")
Pkg.add("DecisionTree")
Pkg.add("Clustering")
Pkg.add("CSV")
Pkg.add("Random")
Pkg.add("LinearAlgebra")
Pkg.add("MultivariateStats")
Pkg.add("Flux")
Pkg.add("DataFrames")
Pkg.add("BSON")
Pkg.add("SafeTestsets")
Pkg.add("Plots")
Pkg.add("Zygote")
Pkg.add("ChainRules")
Pkg.add("MLDatasets")
Pkg.precompile()