using Pkg
path_to_here = @__DIR__
Pkg.activate("$path_to_here")
Pkg.add("GLM")
Pkg.add("Flux.Data.MNIST")
Pkg.add("PyPlot")
Pkg.add("RDatasets")
Pkg.add("throttle")
Pkg.add("crossentropy")
Pkg.add("@epochs")
Pkg.add("LIBSVM")
Pkg.add("Statistics")
Pkg.add("Distributions")
Pkg.add("StatsBase")
Pkg.add("DecisionTree")
Pkg.add("Clustering")
Pkg.add("CSV")
Pkg.add("Random")
Pkg.add("onecold")
Pkg.add("LinearAlgebra")
Pkg.add("Base.Iterators")
Pkg.add("MultivariateStats")
Pkg.add("Flux")
Pkg.add("DataFrames")
Pkg.add("partition")