

test:
	julia --project="../../c01_intro" runtests.jl

test_l0101_helloWorld:
	julia --project="../../c01_intro" test_l0101_helloWorld.jl
test_l0102_comprehension:
	julia --project="../../c01_intro" test_l0102_comprehension.jl
test_l0103_slow:
	julia --project="../../c01_intro" test_l0103_slow.jl
test_l0104_fast:
	julia --project="../../c01_intro" test_l0104_fast.jl
test_l0105_scope:
	julia --project="../../c01_intro" test_l0105_scope.jl
test_l0106_bubbleSort:
	julia --project="../../c01_intro" test_l0106_bubbleSort.jl
test_l0107_polyRoots:
	julia --project="../../c01_intro" test_l0107_polyRoots.jl
test_l0108_multiWayMarkovChainStationary:
	julia --project="../../c01_intro" test_l0108_multiWayMarkovChainStationary.jl
test_l0110_plotSimple:
	julia --project="../../c01_intro" test_l0110_plotSimple.jl
test_l0111_hailstoneHistogram:
	julia --project="../../c01_intro" test_l0111_hailstoneHistogram.jl
test_l0112_graph:
	julia --project="../../c01_intro" test_l0112_graph.jl
test_l0113_imageProcessing:
	julia --project="../../c01_intro" test_l0113_imageProcessing.jl
test_l0114_seedExample:
	julia --project="../../c01_intro" test_l0114_seedExample.jl
test_l0115_piEstimate:
	julia --project="../../c01_intro" test_l0115_piEstimate.jl
test_l0116_lcg:
	julia --project="../../c01_intro" test_l0116_lcg.jl
test_l0117_randomWalks:
	julia --project="../../c01_intro" test_l0117_randomWalks.jl
