
include("$(@__DIR__)/test_l0201_diceSumEven.jl")
include("$(@__DIR__)/test_l0202_passwords.jl")
include("$(@__DIR__)/test_l0203_birthdayProblem.jl")
include("$(@__DIR__)/test_l0204_fishing.jl")
include("$(@__DIR__)/test_l0205_catalan.jl")
include("$(@__DIR__)/test_l0206_sets.jl")
include("$(@__DIR__)/test_l0207_mcFalacy.jl")
include("$(@__DIR__)/test_l0208_secretaryEnvelopes.jl")
include("$(@__DIR__)/test_l0209_occupancyProblem.jl")
include("$(@__DIR__)/test_l0210_independence.jl")
include("$(@__DIR__)/test_l0211_conditionalProbability.jl")
include("$(@__DIR__)/test_l0212_txRxBayes.jl")
include("$(@__DIR__)/test_l0213_montyHall.jl")
