using Pkg
Pkg.activate("~/.julia/environments/v1.5")
Pkg.add("KernelDensity")
Pkg.add("Random")
Pkg.add("Distributions")
Pkg.add("StatsBase")
Pkg.add("HypothesisTests")
Pkg.add("GLM")
# Pkg.add("PyPlot")
Pkg.add("DataFrames")
Pkg.add("CSV")
Pkg.add("CategoricalArrays")
Pkg.add("Plots")