using Pkg
Pkg.activate("~/.julia/environments/v1.5")
Pkg.add("Statistics")
Pkg.add("Random")
Pkg.add("Distributions")
Pkg.add("LinearAlgebra")
Pkg.add("GLM")
# Pkg.add("PyPlot")
Pkg.add("RDatasets")
Pkg.add("PyCall")
Pkg.add("DataFrames")
Pkg.add("CSV")