
environment:
	julia setup.jl

l0201_diceSumEven:
	julia --project=. l0201_diceSumEven.jl
l0202_passwords:
	julia --project=. l0202_passwords.jl
l0203_birthdayProblem:
	julia --project=. l0203_birthdayProblem.jl
l0204_fishing:
	julia --project=. l0204_fishing.jl
l0205_catalan:
	julia --project=. l0205_catalan.jl
l0206_sets:
	julia --project=. l0206_sets.jl
l0207_mcFalacy:
	julia --project=. l0207_mcFalacy.jl
l0208_secretaryEnvelopes:
	julia --project=. l0208_secretaryEnvelopes.jl
l0209_occupancyProblem:
	julia --project=. l0209_occupancyProblem.jl
l0210_independence:
	julia --project=. l0210_independence.jl
l0211_conditionalProbability:
	julia --project=. l0211_conditionalProbability.jl
l0212_txRxBayes:
	julia --project=. l0212_txRxBayes.jl
l0213_montyHall:
	julia --project=. l0213_montyHall.jl