all: l0401_callByValueByReference l0402_shallowDeepCopy l0403_dataframeInspection l0404_dataframeReferencing l0405_dataframeEditing l0406_dataframeCopyDeepCopy l0407_dataframeMissing l0408_dataframeReshape l0409_dataframeOperations l0410_dataframeImputation l0411_summarizingData l0412_meanVectCovMatrixSummary l0413_sampleCovarianceMatrix l0414_manualHistogram l0415_statsPlotsDensity l0416_KDE l0417_ecdf l0418_normalProbabilityPlot l0419_multipleSimplePlot l0420_radialPlot l0421_qqPlot l0422_boxplot l0423_violinPlot l0424_scatterplot l0424_scatterplotMatrix l0425_marginalHists l0426_andrewsPlot l0427_pieChart l0428_barPlots l0429_stackplot l0430_lineSearch l0431_directorySearch l0432_remoteDataServer

environment:
	julia setup.jl

l0401_callByValueByReference:
	julia --project=. l0401_callByValueByReference.jl
l0402_shallowDeepCopy:
	julia --project=. l0402_shallowDeepCopy.jl
l0403_dataframeInspection:
	julia --project=. l0403_dataframeInspection.jl
l0404_dataframeReferencing:
	julia --project=. l0404_dataframeReferencing.jl
l0405_dataframeEditing:
	julia --project=. l0405_dataframeEditing.jl
l0406_dataframeCopyDeepCopy:
	julia --project=. l0406_dataframeCopyDeepCopy.jl
l0407_dataframeMissing:
	julia --project=. l0407_dataframeMissing.jl
l0408_dataframeReshape:
	julia --project=. l0408_dataframeReshape.jl
l0409_dataframeOperations:
	julia --project=. l0409_dataframeOperations.jl
l0410_dataframeImputation:
	julia --project=. l0410_dataframeImputation.jl
l0411_summarizingData:
	julia --project=. l0411_summarizingData.jl
l0412_meanVectCovMatrixSummary:
	julia --project=. l0412_meanVectCovMatrixSummary.jl
l0413_sampleCovarianceMatrix:
	julia --project=. l0413_sampleCovarianceMatrix.jl
l0414_manualHistogram:
	julia --project=. l0414_manualHistogram.jl
l0415_statsPlotsDensity:
	julia --project=. l0415_statsPlotsDensity.jl
l0416_KDE:
	julia --project=. l0416_KDE.jl
l0417_ecdf:
	julia --project=. l0417_ecdf.jl
l0418_normalProbabilityPlot:
	julia --project=. l0418_normalProbabilityPlot.jl
l0419_multipleSimplePlot:
	julia --project=. l0419_multipleSimplePlot.jl
l0420_radialPlot:
	julia --project=. l0420_radialPlot.jl
l0421_qqPlot:
	julia --project=. l0421_qqPlot.jl
l0422_boxplot:
	julia --project=. l0422_boxplot.jl
l0423_violinPlot:
	julia --project=. l0423_violinPlot.jl
l0424_scatterplot:
	julia --project=. l0424_scatterplot.jl
l0424_scatterplotMatrix:
	julia --project=. l0424_scatterplotMatrix.jl
l0425_marginalHists:
	julia --project=. l0425_marginalHists.jl
l0426_andrewsPlot:
	julia --project=. l0426_andrewsPlot.jl
l0427_pieChart:
	julia --project=. l0427_pieChart.jl
l0428_barPlots:
	julia --project=. l0428_barPlots.jl
l0429_stackplot:
	julia --project=. l0429_stackplot.jl
l0430_lineSearch:
	julia --project=. l0430_lineSearch.jl
l0431_directorySearch:
	julia --project=. l0431_directorySearch.jl
l0432_remoteDataServer:
	julia --project=. l0432_remoteDataServer.jl