all: l086_simpLinRegHypTst l0801_polyInterpolate l0802_bestFitLine l0803_leastSqMethods l0804_usingGLM l0805_distRegEstimators l0807_confPredBands l0808_anscombeQuartet l0810_multiLinReg l0811_collinearity l0812_nonlinearGLM l0813_categoricalReg l0813_multiLinear l0814_categoricalRegInteraction l0814_interaction l0815_simpsonsParadox l0816_backwardElimination l0816_stepwiseRegression l0817_lassoSelection l0818_logisticReg l0819_exploreGLM l0820_EDAts l0821_linearForecast l0822_correlogram l0823_leastSqSGD l0824_residualAnalysis

Project.toml:
	julia setup.jl

l086_simpLinRegHypTst:
	julia --project=. l086_simpLinRegHypTst.jl
l0801_polyInterpolate:
	julia --project=. l0801_polyInterpolate.jl
l0802_bestFitLine:
	julia --project=. l0802_bestFitLine.jl
l0803_leastSqMethods:
	julia --project=. l0803_leastSqMethods.jl
l0804_usingGLM:
	julia --project=. l0804_usingGLM.jl
l0805_distRegEstimators:
	julia --project=. l0805_distRegEstimators.jl
l0807_confPredBands:
	julia --project=. l0807_confPredBands.jl
l0808_anscombeQuartet:
	julia --project=. l0808_anscombeQuartet.jl
l0810_multiLinReg:
	julia --project=. l0810_multiLinReg.jl
l0811_collinearity:
	julia --project=. l0811_collinearity.jl
l0812_nonlinearGLM:
	julia --project=. l0812_nonlinearGLM.jl
l0813_categoricalReg:
	julia --project=. l0813_categoricalReg.jl
l0813_multiLinear:
	julia --project=. l0813_multiLinear.jl
l0814_categoricalRegInteraction:
	julia --project=. l0814_categoricalRegInteraction.jl
l0814_interaction:
	julia --project=. l0814_interaction.jl
l0815_simpsonsParadox:
	julia --project=. l0815_simpsonsParadox.jl
l0816_backwardElimination:
	julia --project=. l0816_backwardElimination.jl
l0816_stepwiseRegression:
	julia --project=. l0816_stepwiseRegression.jl
l0817_lassoSelection:
	julia --project=. l0817_lassoSelection.jl
l0818_logisticReg:
	julia --project=. l0818_logisticReg.jl
l0819_exploreGLM:
	julia --project=. l0819_exploreGLM.jl
l0820_EDAts:
	julia --project=. l0820_EDAts.jl
l0821_linearForecast:
	julia --project=. l0821_linearForecast.jl
l0822_correlogram:
	julia --project=. l0822_correlogram.jl
l0823_leastSqSGD:
	julia --project=. l0823_leastSqSGD.jl
l0824_residualAnalysis:
	julia --project=. l0824_residualAnalysis.jl