all: l0301_randomVariable l0302_discreteContinuous l0303_meanIntegration l0304_varianceTransformation l0305_cdfFromPdf l0306_inverseCDF l0307_mgf l0308_weightVector l0309_triangularDist l0310_distributionDescriptors l0311_basicDistRand l0312_triangularDistInv l0313_discreteDists l0314_uniformDiscreteDice l0315_binomialCoinFlip l0316_geometric l0317_negativeBinomial l0318_hypergeometric l0319_poisson l0320_continuousDists l0321_continuousUniform l0322_expGeom l0323_gammaDist l0324_betaDist l0325_gammafunctionIntegration l0326_weibullHazard l0327_normalCalculus l0328_rayleigh l0329_normalDistribution l0330_cauchyCMA l0331_jointPDF l0332_multiRVgeneration l0333_multiDimensionalIntegration l0334_bivariateNormal

clean:
	find . -type f -name "*.png" -exec rm {} \;

environment:
	julia setup.jl

l0301_random_variable_bar.png:
	julia --project=. l0301_randomVariable.jl
l0302_discreteContinuous:
	julia --project=. l0302_discreteContinuous.jl
l0303_meanIntegration:
	julia --project=. l0303_meanIntegration.jl
l0304_varianceTransformation:
	julia --project=. l0304_varianceTransformation.jl
l0305_cdfFromPdf:
	julia --project=. l0305_cdfFromPdf.jl
l0306_inverseCDF:
	julia --project=. l0306_inverseCDF.jl
l0307_mgf:
	julia --project=. l0307_mgf.jl
l0308_weightVector:
	julia --project=. l0308_weightVector.jl
l0309_triangularDist:
	julia --project=. l0309_triangularDist.jl
l0310_distributionDescriptors:
	julia --project=. l0310_distributionDescriptors.jl
l0311_basicDistRand:
	julia --project=. l0311_basicDistRand.jl
l0312_triangularDistInv:
	julia --project=. l0312_triangularDistInv.jl
l0313_discreteDists:
	julia --project=. l0313_discreteDists.jl
l0314_uniformDiscreteDice:
	julia --project=. l0314_uniformDiscreteDice.jl
l0315_binomialCoinFlip:
	julia --project=. l0315_binomialCoinFlip.jl
l0316_geometric:
	julia --project=. l0316_geometric.jl
l0317_negativeBinomial:
	julia --project=. l0317_negativeBinomial.jl
l0318_hypergeometric:
	julia --project=. l0318_hypergeometric.jl
l0319_poisson:
	julia --project=. l0319_poisson.jl
l0320_continuousDists:
	julia --project=. l0320_continuousDists.jl
l0321_continuousUniform:
	julia --project=. l0321_continuousUniform.jl
l0322_expGeom:
	julia --project=. l0322_expGeom.jl
l0323_gammaDist:
	julia --project=. l0323_gammaDist.jl
l0324_betaDist:
	julia --project=. l0324_betaDist.jl
l0325_gammafunctionIntegration:
	julia --project=. l0325_gammafunctionIntegration.jl
l0326_weibullHazard:
	julia --project=. l0326_weibullHazard.jl
l0327_normalCalculus:
	julia --project=. l0327_normalCalculus.jl
l0328_rayleigh:
	julia --project=. l0328_rayleigh.jl
l0329_normalDistribution:
	julia --project=. l0329_normalDistribution.jl
l0330_cauchyCMA:
	julia --project=. l0330_cauchyCMA.jl
l0331_jointPDF:
	julia --project=. l0331_jointPDF.jl
l0332_multiRVgeneration:
	julia --project=. l0332_multiRVgeneration.jl
l0333_multiDimensionalIntegration:
	julia --project=. l0333_multiDimensionalIntegration.jl
l0334_bivariateNormal:
	julia --project=. l0334_bivariateNormal.jl