PROJECT="/home/thom/.julia/environments/StatisticsWithJulia1.9"

test:
	julia --project=${PROJECT} runtests.jl

test_l0301_randomVariable:
	julia --project=${PROJECT} test_l0301_randomVariable.jl
test_l0302_discreteContinuous:
	julia --project=${PROJECT} test_l0302_discreteContinuous.jl
test_l0303_meanIntegration:
	julia --project=${PROJECT} test_l0303_meanIntegration.jl
test_l0304_varianceTransformation:
	julia --project=${PROJECT} test_l0304_varianceTransformation.jl
test_l0305_cdfFromPdf:
	julia --project=${PROJECT} test_l0305_cdfFromPdf.jl
test_l0306_inverseCDF:
	julia --project=${PROJECT} test_l0306_inverseCDF.jl
test_l0307_mgf:
	julia --project=${PROJECT} test_l0307_mgf.jl
test_l0308_weightVector:
	julia --project=${PROJECT} test_l0308_weightVector.jl
test_l0309_triangularDist:
	julia --project=${PROJECT} test_l0309_triangularDist.jl
test_l0310_distributionDescriptors:
	julia --project=${PROJECT} test_l0310_distributionDescriptors.jl
test_l0311_basicDistRand:
	julia --project=${PROJECT} test_l0311_basicDistRand.jl
test_l0312_triangularDistInv:
	julia --project=${PROJECT} test_l0312_triangularDistInv.jl
test_l0313_discreteDists:
	julia --project=${PROJECT} test_l0313_discreteDists.jl
test_l0314_uniformDiscreteDice:
	julia --project=${PROJECT} test_l0314_uniformDiscreteDice.jl
test_l0315_binomialCoinFlip:
	julia --project=${PROJECT} test_l0315_binomialCoinFlip.jl
test_l0316_geometric:
	julia --project=${PROJECT} test_l0316_geometric.jl
test_l0317_negativeBinomial:
	julia --project=${PROJECT} test_l0317_negativeBinomial.jl
test_l0318_hypergeometric:
	julia --project=${PROJECT} test_l0318_hypergeometric.jl
test_l0319_poisson:
	julia --project=${PROJECT} test_l0319_poisson.jl
test_l0320_continuousDists:
	julia --project=${PROJECT} test_l0320_continuousDists.jl
test_l0321_continuousUniform:
	julia --project=${PROJECT} test_l0321_continuousUniform.jl
test_l0322_expGeom:
	julia --project=${PROJECT} test_l0322_expGeom.jl
test_l0323_gammaDist:
	julia --project=${PROJECT} test_l0323_gammaDist.jl
test_l0324_betaDist:
	julia --project=${PROJECT} test_l0324_betaDist.jl
test_l0325_gammafunctionIntegration:
	julia --project=${PROJECT} test_l0325_gammafunctionIntegration.jl
test_l0326_weibullHazard:
	julia --project=${PROJECT} test_l0326_weibullHazard.jl
test_l0327_normalCalculus:
	julia --project=${PROJECT} test_l0327_normalCalculus.jl
test_l0328_rayleigh:
	julia --project=${PROJECT} test_l0328_rayleigh.jl
test_l0329_normalDistribution:
	julia --project=${PROJECT} test_l0329_normalDistribution.jl
test_l0330_cauchyCMA:
	julia --project=${PROJECT} test_l0330_cauchyCMA.jl
test_l0331_jointPDF:
	julia --project=${PROJECT} test_l0331_jointPDF.jl
test_l0332_multiRVgeneration:
	julia --project=${PROJECT} test_l0332_multiRVgeneration.jl
test_l0333_multiDimensionalIntegration:
	julia --project=${PROJECT} test_l0333_multiDimensionalIntegration.jl
test_l0334_bivariateNormal:
	julia --project=${PROJECT} test_l0334_bivariateNormal.jl