
include("$(@__DIR__)/test_l0101_helloWorld.jl")
include("$(@__DIR__)/test_l0102_comprehension.jl")
include("$(@__DIR__)/test_l0103_slow.jl")
include("$(@__DIR__)/test_l0104_fast.jl")
include("$(@__DIR__)/test_l0105_scope.jl")
include("$(@__DIR__)/test_l0106_bubbleSort.jl")
include("$(@__DIR__)/test_l0107_polyRoots.jl")
include("$(@__DIR__)/test_l0108_multiWayMarkovChainStationary.jl")
include("$(@__DIR__)/test_l0110_plotSimple.jl")
include("$(@__DIR__)/test_l0111_hailstoneHistogram.jl")
include("$(@__DIR__)/test_l0113_imageProcessing.jl")
include("$(@__DIR__)/test_l0112_graph.jl")
include("$(@__DIR__)/test_l0114_seedExample.jl")
include("$(@__DIR__)/test_l0115_piEstimate.jl")
include("$(@__DIR__)/test_l0116_lcg.jl")
include("$(@__DIR__)/test_l0117_randomWalks.jl")
include("$(@__DIR__)/test_l0121_usingC.jl")