include("$(@__DIR__)/test_l0601_onePopVKnown.jl")
include("$(@__DIR__)/test_l0602_onePopVUnknown.jl")
include("$(@__DIR__)/test_l0603_twoPopVKnown.jl")
include("$(@__DIR__)/test_l0604_twoPopMVUnknownAEqual.jl")
include("$(@__DIR__)/test_l0605_twoPopMVUnknownAUnequal.jl")
# include("$(@__DIR__)/test_l0606_vDOF_comparison.jl")
# include("$(@__DIR__)/test_l0607_proportionCI.jl")
# include("$(@__DIR__)/test_l0608_proportionCIsampleSize.jl")
# include("$(@__DIR__)/test_l0609_propCIcoverageAccuracy.jl")
# include("$(@__DIR__)/test_l0610_varianceCI.jl")
# include("$(@__DIR__)/test_l0611_sampleVarDists.jl")
# include("$(@__DIR__)/test_l0612_varianceCIalphas.jl")
# include("$(@__DIR__)/test_l0613_bCI.jl")
# include("$(@__DIR__)/test_l0614_bootstrapCI.jl")
# include("$(@__DIR__)/test_l0615_predictionInterval.jl")
# include("$(@__DIR__)/test_l0616_credible.jl")
