using Pkg
Pkg.activate("~/.julia/environments/v1.5")
Pkg.add("PackageCompiler")
Pkg.add("GLM")
# Pkg.add("PyPlot")
Pkg.add("RDatasets")
Pkg.add("LIBSVM")
Pkg.add("Statistics")
Pkg.add("Distributions")
Pkg.add("StatsBase")
Pkg.add("DecisionTree")
Pkg.add("Clustering")
Pkg.add("CSV")
Pkg.add("Random")
Pkg.add("LinearAlgebra")
Pkg.add("MultivariateStats")
Pkg.add("DataFrames")
Pkg.add("BSON")
Pkg.add("SafeTestsets")
Pkg.add("Plots")
Pkg.add("ChainRules")
Pkg.add("MLDatasets")
Pkg.add("Measures")
Pkg.add("Flux")
Pkg.add("Zygote")
