name: ContinuousIntegration

on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  setup_and_test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: [ '1.4', '1.5', '1.6', '1.7', '1.8', '1.9', '1.10' ]
    services:
      apt-cache:
        packages: libqt5widgets5
    steps:
      - name: Setup Julia and Restore Cached Julia dependencies
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
        env:
          JULIA_DEPOT_PATH: ~/.julia
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install libraries
        run: |
          julia --project=~/.julia/environments/v${{ matrix.version }} \
          -e 'using Pkg; Pkg.instantiate()'
      - name: Run Tests
        run: |
          julia --project=~/.julia/environments/v${{ matrix.version }} \
          -e 'using Pkg; Pkg.test()'

  c01_intro:
    name: c01_intro on Julia ${{ matrix.version }}
    needs: setup_and_test
    runs-on: ubuntu-latest
    steps:
      - name: Run Tests c01_intro step
        working-directory: src/c01_intro/tests
        run: julia --project=~/.julia/environments/v${{ matrix.version }} runtests.jl

  c02_probability:
    name: c02_probability on Julia ${{ matrix.version }}
    needs: setup_and_test
    runs-on: ubuntu-latest
    steps:
      - name: Run Tests c02_probability step
        working-directory: src/c02_probability/tests
        run: julia --project=~/.julia/environments/v${{ matrix.version }} runtests.jl

  c03_distribution:
    name: c03_distribution on Julia ${{ matrix.version }}
    needs: setup_and_test
    runs-on: ubuntu-latest
    steps:
      - name: Run Tests c03_distribution step
        working-directory: src/c03_distribution/tests
        run: julia --project=~/.julia/environments/v${{ matrix.version }} runtests.jl

  c04_data:
    name: c04_data on Julia ${{ matrix.version }}
    needs: setup_and_test
    runs-on: ubuntu-latest
    steps:
      - name: Run Tests c04_data step
        working-directory: src/c04_data/tests
        run: julia --project=~/.julia/environments/v${{ matrix.version }} runtests.jl

  c05_inference:
    name: c05_inference on Julia ${{ matrix.version }}
    needs: setup_and_test
    runs-on: ubuntu-latest
    steps:
      - name: Run Tests c05_inference step
        working-directory: src/c05_inference/tests
        run: julia --project=~/.julia/environments/v${{ matrix.version }} runtests.jl
