name: ContinuousIntegration

on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  test:
    name: Julia ${{ matrix.version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: [ '1.4', '1.5', '1.6', '1.7', '1.8', '1.9', '1.10' ]
    steps:
      - name: Setup Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
        env:
          JULIA_DEPOT_PATH: ~/.julia

      - name: Restore Cached Julia dependencies
        uses: actions/cache/restore@v3
        with:
          path: ~/.julia
          key: ${{ runner.os }}-julia-${{ matrix.version }}-${{ hashFiles('scripts/setup.jl') }}

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install testing_library
        working-directory: src/testing_library
        run: julia --project=~/.julia/environments/v${{ matrix.version }} dev.jl

      - name: Install io_library
        working-directory: src/io_library
        run: julia --project=~/.julia/environments/v${{ matrix.version }} dev.jl

      - name: Install c01_intro
        working-directory: src/c01_intro
        run: julia --project=~/.julia/environments/v${{ matrix.version }} dev.jl

#      - name: Install c02_probability
#        working-directory: src/c02_probability
#        run: julia --project=~/.julia/environments/v${{ matrix.version }} dev.jl
#
#      - name: Install c03_distribution
#        working-directory: src/c03_distribution
#        run: julia --project=~/.julia/environments/v${{ matrix.version }} dev.jl
#
#      - name: Install c04_data
#        working-directory: src/c04_data
#        run: julia --project=~/.julia/environments/v${{ matrix.version }} dev.jl
#
#      - name: Install c05_inference
#        working-directory: src/c05_inference
#        run: julia --project=~/.julia/environments/v${{ matrix.version }} dev.jl
#
#      - name: Install c06_confidence
#        working-directory: src/c06_confidence
#        run: julia --project=~/.julia/environments/v${{ matrix.version }} dev.jl
#
#      - name: Install c07_hypothesis
#        working-directory: src/c07_hypothesis
#        run: julia --project=~/.julia/environments/v${{ matrix.version }} dev.jl
#
#      - name: Install c08_regression
#        working-directory: src/c08_regression
#        run: julia --project=~/.julia/environments/v${{ matrix.version }} dev.jl
#
#      - name: Install c09_machine_learning
#        working-directory: src/c09_machine_learning
#        run: julia --project=~/.julia/environments/v${{ matrix.version }} dev.jl
#
#      - name: Install c10_simulation
#        working-directory: src/c10_simulation
#        run: julia --project=~/.julia/environments/v${{ matrix.version }} dev.jl
#
#      - name: Install c11_api
#        working-directory: src/c11_api
#        run: julia --project=~/.julia/environments/v${{ matrix.version }} dev.jl
#
#      - name: Install c12_toy_application
#        working-directory: src/c12_toy_application
#        run: julia --project=~/.julia/environments/v${{ matrix.version }} dev.jl
#
#      - name: Install c13_MyApp
#        working-directory: src/c13_MyApp
#        run: julia --project=~/.julia/environments/v${{ matrix.version }} dev.jl
#
#      - name: Install c14_MyLib
#        working-directory: src/c14_MyLib
#        run: julia --project=~/.julia/environments/v${{ matrix.version }} dev.jl

      - name: Run Tests c01_intro
        working-directory: src/c01_intro/tests
        run: julia --project=~/.julia/environments/v${{ matrix.version }} runtests.jl
