name: CreateCache

on:
  workflow_dispatch:

jobs:
  cacher:
    name: Julia ${{ matrix.version }} Cache
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: [ '1.4', '1.5', '1.6', '1.7', '1.8', '1.9' ]
        python-version: ['3.10']
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
        env:
          JULIA_DEPOT_PATH: ~/.julia

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python Dependencies
        run: python -m pip install matplotlib textblob nltk

      - name: Install Julia Dependencies
        run: julia --project=~/.julia/environments/statistics-with-julia setup.jl
        env:
          PYTHON: python

      - name: Cache Julia dependencies
        uses: actions/cache/save@v3
        with:
          path: |
            ~/.julia
          key: ${{ runner.os }}-julia-${{ matrix.version }}-${{ hashFiles('setup.jl') }}

      - name: Cache Python dependencies
        uses: actions/cache/save@v3
        with:
          path: |
            ~/.cache/pip
          key: ${{ runner.os }}-python-${{ matrix.python-version }}-${{ hashFiles('src/c01_CallPython/requirements.txt') }}
