name: Docker Build Base

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build Base
      run: docker build --progress=plain -t ghcr.io/${{ github.repository_owner }}/stats-with-julia-base:latest -f Dockerfile-base .

    - name: Push Base
      run: docker push ghcr.io/${{ github.repository_owner }}/stats-with-julia-base:latest