name: Docker Build Builder

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build Builder image
      run: docker build --progress=plain -t ghcr.io/${{ github.repository_owner }}/stats-with-julia-builder:latest -f Dockerfile-builder .

    - name: Push
      run: docker push ghcr.io/${{ github.repository_owner }}/stats-with-julia-builder:latest
